
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxgdkxacbeuwttrtgxya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Z2RreGFjYmV1d3R0cnRneHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTI4NDMsImV4cCI6MjA2MTc2ODg0M30._oEC2xKGDOxja98RqL3XCYE3-1xhfxn1_UhWiMvV8sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
